CREATE UNIQUE CLUSTERED INDEX [IX_transitionIdentities_K2_4_3_I1]
    ON [dbo].[transitionIdentities]([transitionSystemsID] ASC, [convertedTableID] ASC, [legacyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);

