ALTER TABLE [dbo].[event_comments]
    ADD CONSTRAINT [PK_event_comments_event_commentsID] PRIMARY KEY CLUSTERED ([event_commentsID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

