ALTER TABLE [dbo].[learn_coursetousers]
    ADD CONSTRAINT [PK_learn_coursetousers_courseToUserID] PRIMARY KEY CLUSTERED ([courseToUserID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

