ALTER TABLE [dbo].[vfc_folder]
    ADD CONSTRAINT [vfc_folder$vfcfoldid] UNIQUE NONCLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

