ALTER TABLE [dbo].[ResponseChanges]
    ADD CONSTRAINT [PK_ResponseChanges] PRIMARY KEY CLUSTERED ([responseChangesID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

