ALTER TABLE [dbo].[chat_rooms]
    ADD CONSTRAINT [chat_rooms$idxRoomName] UNIQUE NONCLUSTERED ([room_name] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

