ALTER TABLE [dbo].[plfCampaignSubscriberLists]
    ADD CONSTRAINT [PK_plfCampaignSubscriberLists] PRIMARY KEY CLUSTERED ([campaignSubscriberListId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

