ALTER TABLE [dbo].[plfSuppressionList]
    ADD CONSTRAINT [plfSuppressionListPK] PRIMARY KEY CLUSTERED ([suppressionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

