ALTER TABLE [dbo].[plfLinksClicked]
    ADD CONSTRAINT [PK_plfLinksClicked] PRIMARY KEY CLUSTERED ([plfLinksClickedId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

