ALTER TABLE [dbo].[room_users]
    ADD CONSTRAINT [PK_room_users_room_id] PRIMARY KEY CLUSTERED ([room_id] ASC, [user_id] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

