ALTER TABLE [dbo].[cal_event]
    ADD CONSTRAINT [cal_event$EventID] UNIQUE NONCLUSTERED ([EventID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

