ALTER TABLE [dbo].[ReportDataTypes]
    ADD CONSTRAINT [PK_responseTypes] PRIMARY KEY CLUSTERED ([reportDataTypesID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

