ALTER TABLE [dbo].[plfUsers_Clients]
    ADD CONSTRAINT [plfUsers_ClientsPK] PRIMARY KEY CLUSTERED ([userId_clientId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

