ALTER TABLE [dbo].[contentTraining]
    ADD CONSTRAINT [PK__contentT__3213E83F12DBA5E6] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

