ALTER TABLE [dbo].[pt_todolists]
    ADD CONSTRAINT [PK_pt_todolists_todolistID] PRIMARY KEY CLUSTERED ([todolistID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

