ALTER TABLE [dbo].[vfc_file_keyword_exclusions]
    ADD CONSTRAINT [PK_vfc_file_keyword_exclusions] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

