ALTER TABLE [dbo].[sso_tokens_outgoing]
    ADD CONSTRAINT [PK__sso_toke__3213E83F71D5E0C4] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

