ALTER TABLE [dbo].[fs_contact_agencyids]
    ADD CONSTRAINT [PK_fs_contact_agencyids_id] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

