ALTER TABLE [dbo].[learn_questions]
    ADD CONSTRAINT [PK_learn_questions_questionID] PRIMARY KEY CLUSTERED ([questionID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

