ALTER TABLE [dbo].[cal_event]
    ADD CONSTRAINT [PK_cal_event_EventID] PRIMARY KEY CLUSTERED ([EventID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

