ALTER TABLE [dbo].[cal_eventcategory]
    ADD CONSTRAINT [PK_cal_eventcategory_EventCatID] PRIMARY KEY CLUSTERED ([EventCatID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

