ALTER TABLE [dbo].[features]
    ADD CONSTRAINT [PK_features_FeatureID] PRIMARY KEY CLUSTERED ([FeatureID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

