ALTER TABLE [dbo].[mc_grouptypes_roles]
    ADD CONSTRAINT [PK_mc_grouptypes_roles_id] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

