ALTER TABLE [dbo].[mc_organization_customvalues]
    ADD CONSTRAINT [PK_mc_organization_customvalues_id] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

