ALTER TABLE [dbo].[mc_contact_sme_topics]
    ADD CONSTRAINT [PK_smeExpertsTopics] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

