ALTER TABLE [dbo].[ReportsAvailableOptions]
    ADD CONSTRAINT [PK_ReportsAvailableOptions] PRIMARY KEY CLUSTERED ([optionsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

