ALTER TABLE [dbo].[photos_events]
    ADD CONSTRAINT [PK_photos_events_eid] PRIMARY KEY CLUSTERED ([eid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

