ALTER TABLE [dbo].[update_alerts]
    ADD CONSTRAINT [PK_update_alerts_update_AlertID] PRIMARY KEY CLUSTERED ([update_AlertID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

