ALTER TABLE [dbo].[chat_users]
    ADD CONSTRAINT [PK_chat_users_user_id] PRIMARY KEY CLUSTERED ([user_id] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

