ALTER TABLE [dbo].[pt_user_notify]
    ADD CONSTRAINT [PK_pt_user_notify_userID] PRIMARY KEY CLUSTERED ([userID] ASC, [projectID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

