ALTER TABLE [dbo].[ReportVersionFields]
    ADD CONSTRAINT [PK_ReportVersionFields] PRIMARY KEY CLUSTERED ([reportVersionFieldsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

