ALTER TABLE [dbo].[event_info]
    ADD CONSTRAINT [PK_event_info_event_infoID] PRIMARY KEY CLUSTERED ([event_infoID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

