ALTER TABLE [dbo].[sso_tokens_incoming]
    ADD CONSTRAINT [PK__sso_user__3213E83F6D112BA7] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

