ALTER TABLE [dbo].[pt_client_rates]
    ADD CONSTRAINT [PK_pt_client_rates_rateID] PRIMARY KEY CLUSTERED ([rateID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

