ALTER TABLE [dbo].[pt_categories]
    ADD CONSTRAINT [PK_pt_categories_projectID] PRIMARY KEY CLUSTERED ([projectID] ASC, [categoryID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

