ALTER TABLE [dbo].[tblmeeting]
    ADD CONSTRAINT [PK_tblmeeting_meetingId] PRIMARY KEY CLUSTERED ([meetingId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

