ALTER TABLE [dbo].[plfTemplates]
    ADD CONSTRAINT [plfTemplatesPK] PRIMARY KEY CLUSTERED ([templateId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

