ALTER TABLE [dbo].[pt_svn_link]
    ADD CONSTRAINT [PK_pt_svn_link_linkID] PRIMARY KEY CLUSTERED ([linkID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

