ALTER TABLE [dbo].[mc_membertypes]
    ADD CONSTRAINT [PK_mc_membertypes_MemberTypeID] PRIMARY KEY CLUSTERED ([MemberTypeID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

