ALTER TABLE [dbo].[ResponseGroupOptions]
    ADD CONSTRAINT [PK_responseGroupOptions] PRIMARY KEY CLUSTERED ([responseGroupOptionsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

