ALTER TABLE [dbo].[mtsch_times]
    ADD CONSTRAINT [PK_mtsch_times_mtsch_TimeID] PRIMARY KEY CLUSTERED ([mtsch_TimeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

