ALTER TABLE [dbo].[pt_comments]
    ADD CONSTRAINT [PK_pt_comments_commentID] PRIMARY KEY CLUSTERED ([commentID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

