ALTER TABLE [dbo].[mtsch_opt_outs]
    ADD CONSTRAINT [PK_mtsch_opt_outs_mtsch_optOutID] PRIMARY KEY CLUSTERED ([mtsch_optOutID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

