ALTER TABLE [dbo].[Requests]
    ADD CONSTRAINT [PK_Requests] PRIMARY KEY CLUSTERED ([requestsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

