ALTER TABLE [dbo].[cflm_cross]
    ADD CONSTRAINT [PK_cflm_cross] PRIMARY KEY CLUSTERED ([linkid] ASC, [categoryid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

