ALTER TABLE [dbo].[learn_useranswers]
    ADD CONSTRAINT [PK_learn_useranswers_userAnswerID] PRIMARY KEY CLUSTERED ([userAnswerID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

