ALTER TABLE [dbo].[cal_actiontask]
    ADD CONSTRAINT [PK_cal_actiontask_TaskID] PRIMARY KEY CLUSTERED ([TaskID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

