ALTER TABLE [dbo].[learn_users]
    ADD CONSTRAINT [PK_learn_users_userID] PRIMARY KEY CLUSTERED ([userID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

