ALTER TABLE [dbo].[mc_groups]
    ADD CONSTRAINT [PK_mc_groups_Group_ID] PRIMARY KEY CLUSTERED ([Group_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

