ALTER TABLE [dbo].[Responses]
    ADD CONSTRAINT [PK_reportResponses] PRIMARY KEY CLUSTERED ([responsesID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

