ALTER TABLE [dbo].[vid_videos]
    ADD CONSTRAINT [PK_vid_videos_vid_VideoID] PRIMARY KEY CLUSTERED ([vid_VideoID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

