ALTER TABLE [dbo].[fs_foodag_orgs]
    ADD CONSTRAINT [PK_fs_foodag_orgs] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

