ALTER TABLE [dbo].[cal_location]
    ADD CONSTRAINT [PK_cal_location_LocationID] PRIMARY KEY CLUSTERED ([LocationID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

