ALTER TABLE [dbo].[pt_file_attach]
    ADD CONSTRAINT [PK_pt_file_attach_itemID] PRIMARY KEY CLUSTERED ([itemID] ASC, [fileID] ASC, [type] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

