ALTER TABLE [dbo].[cal_eventnews]
    ADD CONSTRAINT [PK_cal_eventnews_EventNewsID] PRIMARY KEY CLUSTERED ([EventNewsID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

