ALTER TABLE [dbo].[event_invites]
    ADD CONSTRAINT [PK_event_invites_eventInviteID] PRIMARY KEY CLUSTERED ([eventInviteID] ASC, [userID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

