ALTER TABLE [dbo].[plfSubscriberLinksClicked]
    ADD CONSTRAINT [PK_plfSubscriberLinksClicked] PRIMARY KEY CLUSTERED ([subscriberlinkId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

