ALTER TABLE [dbo].[pt_project_components]
    ADD CONSTRAINT [PK_pt_project_components_componentID] PRIMARY KEY CLUSTERED ([componentID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

