ALTER TABLE [dbo].[featuresvotes]
    ADD CONSTRAINT [PK_featuresvotes_FeaturesVotesID] PRIMARY KEY CLUSTERED ([FeaturesVotesID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

