ALTER TABLE [dbo].[pt_clients]
    ADD CONSTRAINT [PK_pt_clients_clientID] PRIMARY KEY CLUSTERED ([clientID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

