ALTER TABLE [dbo].[ResponseGroups]
    ADD CONSTRAINT [PK_ReponseGroups] PRIMARY KEY CLUSTERED ([responseGroupsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

