ALTER TABLE [dbo].[c_domains]
    ADD CONSTRAINT [PK__c_domain__3213E83F43B3E76B] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

