ALTER TABLE [dbo].[mc_quicklinks]
    ADD CONSTRAINT [PK__mc_quick__3213E83F6E4C3B47] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

