ALTER TABLE [dbo].[ReportQuestionTemplates]
    ADD CONSTRAINT [PK_ReportQuestionTemplates] PRIMARY KEY CLUSTERED ([reportQuestionTemplatesID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

