ALTER TABLE [dbo].[mtsch_dates]
    ADD CONSTRAINT [PK_mtsch_dates_mtsch_DateID] PRIMARY KEY CLUSTERED ([mtsch_DateID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

