ALTER TABLE [dbo].[ReportIndicators]
    ADD CONSTRAINT [PK_ReportIndicators] PRIMARY KEY CLUSTERED ([reportIndicatorID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

