ALTER TABLE [dbo].[pt_users]
    ADD CONSTRAINT [PK_pt_users_userID] PRIMARY KEY CLUSTERED ([userID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

