ALTER TABLE [dbo].[ReportGroupOptions]
    ADD CONSTRAINT [PK_ReportGroupOptions] PRIMARY KEY CLUSTERED ([reportGroupOptionsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

