ALTER TABLE [dbo].[rss_rssfeeds]
    ADD CONSTRAINT [PK_rss_rssfeeds_rss_RssFeedID] PRIMARY KEY CLUSTERED ([rss_RssFeedID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

