ALTER TABLE [dbo].[plfCampaigns]
    ADD CONSTRAINT [plfCampaignsPK] PRIMARY KEY CLUSTERED ([campaignId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

