ALTER TABLE [dbo].[pt_screenshots]
    ADD CONSTRAINT [PK_pt_screenshots_fileID] PRIMARY KEY CLUSTERED ([fileID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

