ALTER TABLE [dbo].[ResponseReportingDetails]
    ADD CONSTRAINT [PK__Response__3213E83F7145A7F1] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

