ALTER TABLE [dbo].[mc_sys_alerts]
    ADD CONSTRAINT [PK_mc_sys_alerts_maint_id] PRIMARY KEY CLUSTERED ([maint_id] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

