ALTER TABLE [dbo].[RequestOptions]
    ADD CONSTRAINT [PK_RequestOptions] PRIMARY KEY CLUSTERED ([requestOptionsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

