ALTER TABLE [dbo].[pt_activity]
    ADD CONSTRAINT [PK_pt_activity_activityID] PRIMARY KEY CLUSTERED ([activityID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

