ALTER TABLE [dbo].[learn_scores]
    ADD CONSTRAINT [PK_learn_scores_scoreID] PRIMARY KEY CLUSTERED ([scoreID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

