ALTER TABLE [dbo].[pt_carriers]
    ADD CONSTRAINT [PK_pt_carriers_carrierID] PRIMARY KEY CLUSTERED ([carrierID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

