ALTER TABLE [dbo].[learn_regquestions]
    ADD CONSTRAINT [PK_learn_regquestions_questionID] PRIMARY KEY CLUSTERED ([questionID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

