ALTER TABLE [dbo].[learn_reganswers]
    ADD CONSTRAINT [PK_learn_reganswers_answerID] PRIMARY KEY CLUSTERED ([answerID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

