ALTER TABLE [dbo].[tblmeetingitem]
    ADD CONSTRAINT [PK_tblmeetingitem_meetingItemId] PRIMARY KEY CLUSTERED ([meetingItemId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

