ALTER TABLE [dbo].[mc_contact_affiliations]
    ADD CONSTRAINT [PK__mc_conta__3213E83F3960762A] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

