ALTER TABLE [dbo].[oauth_consumers]
    ADD CONSTRAINT [PK_oauth_consumers] PRIMARY KEY CLUSTERED ([consumer_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

