ALTER TABLE [dbo].[tblgroup]
    ADD CONSTRAINT [PK_tblgroup_groupId] PRIMARY KEY CLUSTERED ([groupId] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

