ALTER TABLE [dbo].[pt_todos]
    ADD CONSTRAINT [PK_pt_todos_todoID] PRIMARY KEY CLUSTERED ([todoID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

