CREATE TABLE [dbo].[smeCategoryRecords] (
    [id]         INT IDENTITY (1, 1) NOT NULL,
    [CategoryID] INT DEFAULT ((0)) NOT NULL,
    [RecordID]   INT NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

