CREATE TABLE [dbo].[Contacts] (
    [id]              UNIQUEIDENTIFIER NOT NULL,
    [Salutation]      NVARCHAR (20)    NULL,
    [JobTitle]        NVARCHAR (255)   NULL,
    [Firstname]       NVARCHAR (50)    NULL,
    [Initial]         NVARCHAR (50)    NULL,
    [Lastname]        NVARCHAR (50)    NULL,
    [Suffix]          NVARCHAR (40)    NULL,
    [Email]           NVARCHAR (50)    NULL,
    [Login]           NVARCHAR (50)    NULL,
    [Password]        NVARCHAR (500)   NULL,
    [salt]            NVARCHAR (35)    NULL,
    [AccessID]        INT              NULL,
    [Expires]         DATETIME2 (0)    NULL,
    [Hits]            INT              NULL,
    [LastLogin]       DATETIME2 (0)    NULL,
    [Status]          NVARCHAR (20)    NULL,
    [ModifiedBy]      NVARCHAR (50)    NULL,
    [DateModified]    DATETIME2 (0)    NULL,
    [datejoined]      DATETIME2 (0)    NULL,
    [membertype]      INT              NULL,
    [photo]           NVARCHAR (120)   NULL,
    [resume]          NVARCHAR (120)   NULL,
    [thumb]           NVARCHAR (120)   NULL,
    [PIN]             INT              NULL,
    [reset]           BIT              NULL,
    [mailsent]        BIT              NULL,
    [sysmember]       INT              NULL,
    [maildate]        DATETIME2 (0)    NULL,
    [updatesent]      DATETIME2 (0)    NULL,
    [updatenum]       INT              NULL,
    [nosend]          BIT              NULL,
    [hidden]          BIT              NULL,
    [security_level]  INT              NULL,
    [review]          BIT              NULL,
    [Q1]              NVARCHAR (50)    NULL,
    [Q2]              NVARCHAR (50)    NULL,
    [Q3]              NVARCHAR (50)    NULL,
    [iAnswer]         NVARCHAR (50)    NULL,
    [ipMac]           NVARCHAR (100)   NULL,
    [frequency_id]    INT              NULL,
    [refer]           INT              NULL,
    [is_active]       BIT              NULL,
    [TimeZone]        NVARCHAR (35)    NULL,
    [usesDaylight]    BIT              NULL,
    [TzOffset]        INT              NULL,
    [iDefault_Quota]  INT              NULL,
    [iDoc_Usage]      DECIMAL (10)     NULL,
    [assist_id]       INT              NULL,
    [layout]          INT              NULL,
    [bTOS]            BIT              NULL,
    [bOnlineNow]      BIT              NULL,
    [uID]             UNIQUEIDENTIFIER NULL,
    [iwkgrplayout]    INT              NULL,
    [sAboutMe]        NVARCHAR (500)   NULL,
    [folder_id]       INT              NULL,
    [signature]       NVARCHAR (MAX)   NULL,
    [dateAdded]       DATETIME2 (0)    NULL,
    [addedBy]         UNIQUEIDENTIFIER NULL,
    [bAuditLock]      BIT              NULL,
    [bProfileUpdate]  BIT              NULL,
    [bexpirereminder] BIT              NULL,
    [bPingSent]       BIT              NULL,
    [dPingDate]       DATETIME2 (0)    NULL,
    [bVerified]       BIT              NULL,
    [verifiedBy]      UNIQUEIDENTIFIER NULL,
    [dVerifiedDate]   DATETIME2 (0)    NULL,
    [inetwork]        INT              NULL
);

