CREATE TABLE [dbo].[plfCampaigns] (
    [campaignId]                       INT            IDENTITY (1, 1) NOT NULL,
    [clientId]                         INT            NULL,
    [campaignName]                     NVARCHAR (255) NULL,
    [campaignSubject]                  NVARCHAR (255) NULL,
    [campaignFromName]                 NVARCHAR (255) NULL,
    [campaignFromEmailAddress]         NVARCHAR (150) NULL,
    [campaignReplyToEmailAddress]      NVARCHAR (150) NULL,
    [campaignEmailType]                NVARCHAR (50)  NULL,
    [campaignHTMLSource]               NVARCHAR (MAX) NULL,
    [campaignOriginalHTMLSource]       NVARCHAR (MAX) NULL,
    [campaignHTMLImported]             NVARCHAR (50)  NULL,
    [campaignHTMLImportedDateTime]     DATETIME       NULL,
    [campaignHTMLLocation]             NVARCHAR (50)  NULL,
    [campaignHTMLLocationData]         NVARCHAR (255) NULL,
    [campaignTextSource]               NVARCHAR (MAX) NULL,
    [campaignTextImported]             NVARCHAR (50)  NULL,
    [campaignEmbedImages]              NVARCHAR (50)  NULL,
    [campaignTextImportedDateTime]     DATETIME       NULL,
    [campaignUID]                      NVARCHAR (255) NULL,
    [campaignSent]                     NVARCHAR (50)  NULL,
    [campaignDateSent]                 DATETIME       NULL,
    [campaignDeliveryType]             NVARCHAR (50)  NULL,
    [campaignDeliveryDateTime]         DATETIME       NULL,
    [campaignReadyForDelivery]         NVARCHAR (50)  NULL,
    [campaignConfirmationEmailAddress] NVARCHAR (150) NULL,
    [campaignConfirmationEmailSent]    NVARCHAR (50)  NULL,
    [campaignNumberOfUnsubscribers]    INT            NULL,
    [campaignDateCreated]              DATETIME       NULL,
    [campaignCreatedByUserId]          INT            NULL,
    [campaignStep1Complete]            NVARCHAR (50)  NULL,
    [campaignStep2Complete]            NVARCHAR (50)  NULL,
    [campaignStep3Complete]            NVARCHAR (50)  NULL,
    [campaignNumberOfLinks]            INT            NULL,
    [campaignContainsJavascript]       NVARCHAR (50)  NULL,
    [campaignContainsExternalCSS]      NVARCHAR (50)  NULL,
    [campaignContainsImages]           NVARCHAR (50)  NULL,
    [campaignContainsUnsubscribeLink]  NVARCHAR (50)  NULL,
    [campaignContainsUTF8]             NVARCHAR (50)  NULL,
    [campaignContainsFlash]            NVARCHAR (50)  NULL
);

