CREATE TABLE [dbo].[vfc_file] (
    [ID]                 INT              IDENTITY (725, 1) NOT NULL,
    [MIMETypeID]         INT              NOT NULL,
    [ParentFolderID]     INT              NOT NULL,
    [iByteSize]          INT              NOT NULL,
    [sName]              NVARCHAR (MAX)   NULL,
    [serverFileName]     NVARCHAR (3000)  NULL,
    [sAuthor]            NVARCHAR (200)   NULL,
    [sSource]            NVARCHAR (200)   NULL,
    [iRevision]          INT              NOT NULL,
    [sTitle]             NVARCHAR (255)   NULL,
    [sSubject]           NVARCHAR (100)   NULL,
    [sLocation]          NVARCHAR (MAX)   NULL,
    [bDeleted]           BIT              NOT NULL,
    [dtCreated]          DATETIME2 (0)    NOT NULL,
    [CreatedByUserID]    INT              NOT NULL,
    [dtUpdated]          DATETIME2 (0)    NOT NULL,
    [UpdatedByUserID]    INT              NULL,
    [dtCheckedOut]       DATETIME2 (0)    NULL,
    [CheckedOutByUserID] INT              NULL,
    [sComments]          NVARCHAR (MAX)   NULL,
    [sDescription]       NVARCHAR (MAX)   NULL,
    [sContentType]       NVARCHAR (30)    NOT NULL,
    [bActive]            BIT              NOT NULL,
    [status]             INT              NOT NULL,
    [threadID]           NVARCHAR (50)    NULL,
    [pLocation]          NVARCHAR (MAX)   NULL,
    [sCheckOutComments]  NVARCHAR (255)   NULL,
    [bLog]               BIT              NOT NULL,
    [iSendLog]           INT              NOT NULL,
    [iViews]             INT              NOT NULL,
    [bShare]             BIT              NOT NULL,
    [bUseAuthor]         BIT              NOT NULL,
    [showGroup]          BIT              NOT NULL,
    [sharegroup]         BIT              NOT NULL,
    [iDownloads]         INT              NOT NULL,
    [dtExpires]          DATETIME2 (0)    NULL,
    [isortOrder]         INT              NOT NULL,
    [iMinorRevision]     INT              NOT NULL,
    [allowComments]      BIT              NULL,
    [thumbs]             BIT              NOT NULL,
    [thumblocation]      NVARCHAR (MAX)   NOT NULL,
    [iComments]          INT              NOT NULL,
    [iPriority]          INT              NOT NULL,
    [bPublic]            BIT              NOT NULL,
    [placeholder]        NVARCHAR (255)   NULL,
    [bsecureview]        BIT              NOT NULL,
    [bencrypted]         BIT              NOT NULL,
    [uid]                UNIQUEIDENTIFIER NOT NULL,
    [swflocation]        NVARCHAR (500)   NULL,
    [customVersionNum]   NVARCHAR (20)    NULL
);

