CREATE TABLE [dbo].[plfCampaignSubscribers] (
    [campaignSubscriberId]   INT            IDENTITY (1, 1) NOT NULL,
    [campaignId]             INT            NULL,
    [subscriberId]           INT            NULL,
    [subscriberEmailAddress] NVARCHAR (255) NULL,
    [subscriberName]         NVARCHAR (255) NULL,
    [subscriberListId]       INT            NULL,
    [subscriberType]         NVARCHAR (50)  NULL,
    [openedEmail]            NVARCHAR (50)  NULL,
    [openedEmailCount]       INT            NULL,
    [openedEmailDateTime]    DATETIME       NULL,
    [bounced]                NVARCHAR (50)  NULL,
    [bouncedDateTime]        DATETIME       NULL,
    [bounceType]             NVARCHAR (255) NULL,
    [linkClicked]            NVARCHAR (50)  NULL,
    [linkClickCount]         INT            NULL,
    [unsubscribed]           NVARCHAR (50)  NULL,
    [unsubscribedDateTime]   DATETIME       NULL,
    [campaignEmailSent]      NVARCHAR (50)  NULL,
    [userAgent]              NVARCHAR (255) NULL,
    [mail_userAgent]         NVARCHAR (255) NULL,
    [userIPAddress]          NVARCHAR (150) NULL,
    [userCountryCode]        NVARCHAR (20)  NULL,
    [userOpenMethod]         NVARCHAR (50)  NULL,
    CHECK ([bounced]='YES' OR [bounced]='NO'),
    CHECK ([campaignEmailSent]='YES' OR [campaignEmailSent]='NO'),
    CHECK ([linkClicked]='YES' OR [linkClicked]='NO'),
    CHECK ([openedEmail]='YES' OR [openedEmail]='NO'),
    CHECK ([subscriberType]='LIST' OR [subscriberType]='MANUAL'),
    CHECK ([unsubscribed]='YES' OR [unsubscribed]='NO'),
    CHECK ([userOpenMethod]='IMAGE' OR [userOpenMethod]='CLICK')
);

