CREATE TABLE [dbo].[ReportFilters] (
    [reportFiltersID]        UNIQUEIDENTIFIER NOT NULL,
    [reportVersionsID]       UNIQUEIDENTIFIER NOT NULL,
    [displayOrder]           INT              NOT NULL,
    [buttonLabel]            NVARCHAR (50)    NOT NULL,
    [title]                  NVARCHAR (50)    NOT NULL,
    [information]            NVARCHAR (1000)  NOT NULL,
    [outputReportGroups]     NVARCHAR (MAX)   NULL,
    [filterQuestions]        NVARCHAR (MAX)   NOT NULL,
    [outputQuestions]        NVARCHAR (MAX)   NOT NULL,
    [groupByQuestion]        NVARCHAR (MAX)   NOT NULL,
    [filterOnEnteredBy]      BIT              NULL,
    [outputEnteredBy]        BIT              NULL,
    [filterEnteredDate]      BIT              NULL,
    [outputEnteredDate]      BIT              NULL,
    [isSubmission]           BIT              NULL,
    [filterOnUpdatedBy]      BIT              NOT NULL,
    [outputUpdatedBy]        BIT              NOT NULL,
    [filterOnUpdatedDate]    BIT              NOT NULL,
    [outputUpdatedDate]      BIT              NOT NULL,
    [OutputResponseID]       BIT              NOT NULL,
    [GridOutput]             NVARCHAR (2)     NOT NULL,
    [GridOutputValues]       NVARCHAR (2)     NOT NULL,
    [GridOutputDateFormat]   NVARCHAR (20)    NOT NULL,
    [ChartOutput]            NVARCHAR (2)     NOT NULL,
    [ChartOutputIDs]         NVARCHAR (MAX)   NULL,
    [ChartOutputValues]      NVARCHAR (2)     NOT NULL,
    [ChartOutputByDate]      NVARCHAR (1)     NOT NULL,
    [ChartOutputDateFormat]  NVARCHAR (20)    NOT NULL,
    [ChartOutputAllAverage]  BIT              NOT NULL,
    [IsActive]               BIT              NOT NULL,
    [GridOutputResponseLink] BIT              NOT NULL,
    [CustomReport]           NVARCHAR (150)   NULL
);

