CREATE TABLE [dbo].[pt_projects] (
    [projectID]          UNIQUEIDENTIFIER NOT NULL,
    [ownerID]            UNIQUEIDENTIFIER NULL,
    [clientID]           UNIQUEIDENTIFIER NULL,
    [name]               NVARCHAR (50)    NULL,
    [description]        NVARCHAR (MAX)   NULL,
    [display]            BIT              NULL,
    [ticketPrefix]       NVARCHAR (20)    NULL,
    [added]              DATETIME2 (0)    NULL,
    [addedBy]            UNIQUEIDENTIFIER NOT NULL,
    [status]             NVARCHAR (8)     NULL,
    [svnurl]             NVARCHAR (100)   NULL,
    [svnuser]            NVARCHAR (20)    NULL,
    [svnpass]            NVARCHAR (20)    NULL,
    [logo_img]           NVARCHAR (150)   NULL,
    [allow_reg]          BIT              NULL,
    [allow_def_rates]    BIT              NULL,
    [reg_file_view]      INT              NULL,
    [reg_file_edit]      INT              NULL,
    [reg_file_comment]   INT              NULL,
    [reg_issue_view]     INT              NULL,
    [reg_issue_edit]     INT              NULL,
    [reg_issue_assign]   INT              NULL,
    [reg_issue_resolve]  INT              NULL,
    [reg_issue_close]    INT              NULL,
    [reg_issue_comment]  INT              NULL,
    [reg_msg_view]       INT              NULL,
    [reg_msg_edit]       INT              NULL,
    [reg_msg_comment]    INT              NULL,
    [reg_mstone_view]    INT              NULL,
    [reg_mstone_edit]    INT              NULL,
    [reg_mstone_comment] INT              NULL,
    [reg_time_view]      INT              NULL,
    [reg_time_edit]      INT              NULL,
    [reg_todolist_view]  INT              NULL,
    [reg_todolist_edit]  INT              NULL,
    [reg_todo_edit]      INT              NULL,
    [reg_todo_comment]   INT              NULL,
    [reg_bill_view]      INT              NULL,
    [reg_bill_edit]      INT              NULL,
    [reg_bill_rates]     INT              NULL,
    [reg_bill_invoices]  INT              NULL,
    [reg_bill_markpaid]  INT              NULL,
    [reg_report]         INT              NULL,
    [reg_svn]            INT              NULL,
    [tab_billing]        INT              NULL,
    [tab_files]          INT              NULL,
    [tab_issues]         INT              NULL,
    [tab_msgs]           INT              NULL,
    [tab_mstones]        INT              NULL,
    [tab_svn]            INT              NULL,
    [tab_time]           INT              NULL,
    [tab_todos]          INT              NULL,
    [issue_svn_link]     INT              NULL,
    [issue_timetrack]    INT              NULL
);

