ALTER TABLE [dbo].[smeUsers]
    ADD CONSTRAINT [PK__smeAgent__3213E83F351BAF51] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

