ALTER TABLE [dbo].[smeLevels]
    ADD CONSTRAINT [PK__smeLevel__3213E83F3E1D39E1] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

