ALTER TABLE [dbo].[smeTypes]
    ADD CONSTRAINT [PK__smeTypes__3213E83F43D61337] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

