ALTER TABLE [dbo].[smeCategories]
    ADD CONSTRAINT [PK__smeCateg__3213E83F3864608B] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

