ALTER TABLE [dbo].[smeAcademicSpecialty]
    ADD CONSTRAINT [PK__smeAcade__3213E83F3587F3E0] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

