ALTER TABLE [dbo].[smeRecords]
    ADD CONSTRAINT [PK__smeRecor__3213E83F40F9A68C] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

