ALTER TABLE [dbo].[smeAcademicDegreeTypes]
    ADD CONSTRAINT [aaaaacEducationDegrees_PK] PRIMARY KEY NONCLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

