CREATE NONCLUSTERED INDEX [_dta_index_vfc_fileace_52_267616492__K9_K10_K1_6]
    ON [dbo].[vfc_fileace]([iuserid] ASC, [id] ASC, [FileID] ASC)
    INCLUDE([igrouproleid]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

