CREATE NONCLUSTERED INDEX [IX_vfc_file_K14D_K1_9_10_19]
    ON [dbo].[vfc_file]([dtCreated] DESC, [ID] ASC)
    INCLUDE([iRevision], [sTitle], [CheckedOutByUserID]) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

